repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: 'mkdocs.yml|charts/.*'
      - id: check-json
      - id: end-of-file-fixer
        exclude: ^scripts/templates/
      - id: trailing-whitespace
        exclude: ^scripts/templates/
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
